services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@mail.xyz
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin


  frontend:
    build:
      target: dev
    volumes:
      - ./src/frontend:/app

volumes:
  pgadmin-data:
