services:
  hackback.api:
    image: ${DOCKER_REGISTRY-}hackbackapi
    build:
      context: .
      dockerfile: HackBack.API/Dockerfile
    networks:
    - mikulearn_default
    ports:
    - 7090:8080
    - 7091:8081
 

networks:
  mikulearn_default:
    name: mikulearn_default
    driver: bridge
    external: true
  